### ISSUE TITLE
WordPress 4.1 asks for FTP Connection Information

### ISSUE THREAD

**Issue by joelchen** [dorwardv/nginx_hhvm_wordpress_sqlite#1]
Hi Wardy,

I have the issue of WordPress prompting FTP Connection Information when installing/deleting plugins after upgrade to WordPress 4.1, whereas I could install/delete plugins directly before. Putting define('FS_METHOD', 'direct'); in wp-config.php solves the issue for me. Do you get it in your servers?

Warmest Regards,
Joel

**Comment by dorwardv** [comment]
Hi Joel,

I encountered that one before but that was for version 3.6 and 3.7 it has
something to do with wordpress forcing ftp.  But then I was told in the IRC
channel that using 'direct' is not a good practice.  It's even mentioned in
the documentation, so I didn't bother to fix the problem and ince then I
setup an ftpserver with my wordpress installations.

Cheers,
Wardy

**Comment by dorwardv** [comment]
Hi Joel,

I forgot to attach the link to the documentation.
Here it is.  http://codex.wordpress.org/Editing_wp-config.php

Cheers,
Wardy
